version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: devpulse-postgres
    environment:
      POSTGRES_DB: devpulse
      POSTGRES_USER: sumit
      POSTGRES_PASSWORD: sumit123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devpulse_user -d devpulse"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
