spring:
  application:
    name: devpulse

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devpulse}
    username: ${SPRING_DATASOURCE_USERNAME:sumit}
    password: ${SPRING_DATASOURCE_PASSWORD:sumit123}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.devpulse: INFO
    org.hibernate.SQL: WARN

github:
  token: ${GITHUB_TOKEN:}    

ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  model-name: ${OLLAMA_MODEL_NAME:llama3.2} 

groq:
  api-key: ${GROQ_API_KEY:}
  model-name: ${GROQ_MODEL_NAME:llama-3.3-70b-versatile}