-- V1__init_tenants.sql
--
-- Flyway runs this file exactly once, in order, tracked by a `flyway_schema_history`
-- table it creates automatically. If you ever need to change this table later,
-- you do NOT edit this file — you create V2__something.sql instead.
-- This is what makes schema changes auditable and reproducible across every
-- environment (your laptop, CI, production) — same principle as Git for code.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- pgcrypto gives us gen_random_uuid() for UUID primary keys.
-- We use UUIDs instead of auto-increment integers so tenant IDs are
-- non-guessable and safe to expose in API responses.

CREATE TABLE tenants (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(255) NOT NULL,
    api_key_hash    VARCHAR(255) NOT NULL UNIQUE,
    plan            VARCHAR(50) NOT NULL DEFAULT 'FREE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- We index api_key_hash because every authenticated API request will look up
-- a tenant by their hashed key. Without this index, that lookup becomes a
-- full table scan as soon as you have more than a handful of tenants.
CREATE INDEX idx_tenants_api_key_hash ON tenants(api_key_hash);

COMMENT ON COLUMN tenants.api_key_hash IS
  'BCrypt hash of the API key. The plaintext key is shown to the user exactly once at creation and never stored.';
